In [1]:
import os
import os.path
import torch
import numpy as np
import h5py
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [5]:
root = 'D:/datasets/CRN'

In [6]:
train_path = root + '/train_data.h5'

In [7]:
data = h5py.File(train_path, 'r')
data.keys()

<KeysViewHDF5 ['complete_pcds', 'incomplete_pcds', 'labels']>

In [18]:
for key in data.keys():
    print(data[key].shape)

(28974, 2048, 3)
(28974, 2048, 3)
(28974,)


In [19]:
print(data['complete_pcds'][0])
pcd_np = data['complete_pcds'][5]

[[-0.193039    0.0408779   0.3669163 ]
 [-0.01716815 -0.05691997 -0.4089964 ]
 [ 0.26603886 -0.07147107  0.1522262 ]
 ...
 [-0.23215142  0.01986598 -0.39245927]
 [-0.18092135  0.01699539  0.23610254]
 [-0.08672868  0.04085426 -0.33577806]]


In [17]:
pcd_o3d = o3d.geometry.PointCloud()  # create point cloud object
pcd_o3d.points = o3d.utility.Vector3dVector(pcd_np)  # set pcd_np as the point cloud points

# Visualize:
o3d.visualization.draw_geometries([pcd_o3d])

In [26]:
import torch.nn as nn
from torchsummary import summary

In [46]:
class net1(nn.Module):
  def __init__(self):
    super().__init__()
    # self.conv = nn.Linear(3,4)
    self.tens = nn.Parameter(torch.ones(3,4))                       # This won't show up in a parameter list 
    
  # def forward(self, x):
  #   return self.conv(x)

myNet = net1()
print(list(myNet.parameters()))
# print(myNet)
# summary(myNet, (4,3))

[Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)]
