In [1]:
import numpy as np
import open3d as o3d
import mcubes

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## GT visualization

In [5]:
gt_root = "D:/Projects/Datasets/shapenet/03001627/2a6b8437623a374e504721639e19f609/input_4.npz"
gt_data = np.load(gt_root)
print(gt_data.files)

['tsdf', 'voxels']


In [3]:
gt_voxels = gt_data['tsdf']

In [4]:
vertices, triangles = mcubes.marching_cubes(gt_voxels, 0)
mcubes.export_obj(vertices, triangles, 'f609_input_4.obj')

## Prediction visualization


In [10]:
root = "D:/Projects/JRF/related_code/shape_completion/PatchComplete/output/shapenet/02773838/1b84dededd445058e44a5473032f38f/input_4_pred.npz"
data = np.load(root)
print(data.files)

['predicted_voxels']


In [11]:
voxels = data['predicted_voxels']
# print(voxels)

In [12]:
vertices, triangles = mcubes.marching_cubes(voxels, 0)

In [13]:
print(vertices)
print("vertices shape: ", vertices.shape)
print(triangles)
print("triangles shape: ", triangles.shape)

[[ 5.91326348  8.         15.        ]
 [ 6.          7.1458829  15.        ]
 [ 6.          8.         14.82340128]
 ...
 [25.00002129 19.         15.        ]
 [26.00009551 13.         15.        ]
 [26.01756695 13.         16.        ]]
vertices shape:  (1435, 3)
[[   2    0    1]
 [   1    3    4]
 [   0    3    1]
 ...
 [1434 1419 1433]
 [1421 1419 1434]
 [1434 1417 1421]]
triangles shape:  (2806, 3)


In [14]:
mcubes.export_obj(vertices, triangles, '2_input_4_pred.obj')

## Priors Visualization


In [15]:
root = "patchComplete/priors/02747177_2.npy"
data = np.load(root)
# print(data)

In [16]:
vertices, triangles = mcubes.marching_cubes(data, 0)
mcubes.export_obj(vertices, triangles, 'prior_02747177_2.obj')